Preston/11 data finalization
kaimed1/capstone pull request #14
Opened 2024-10-23 23:59 UTC by proesslet

This only includes the table for "Teams" which can be used for making drop downs for selection on the frontend. The rest of the db will come in a later PR

2024-10-24 00:00 UTC, proesslet commented on backend/data/Teams.csv
@nathanstephani12 Can you take a glance over this and just make sure that the new version is correct. I had some merge conflicts like you had when we had worked on it together, and I just want to make sure the team names still match what you changed them to

2024-10-24 00:03 UTC, Metzark approved these changes

2024-10-24 00:38 UTC, Karly1234 approved these changes

2024-10-24 03:02 UTC, nathanstephani12 requested changes

2024-10-24 03:02 UTC, nathanstephani12 commented on backend/data/Teams.csv
The school column in Teams.csv should be as they were before your changes. I had edited them to match up with sports-reference so that it would be easier to pull in data in the future. Changes should be reverted before merging in this branch.

2024-10-28 16:57 UTC, nathanstephani12 approved these changes

2024-10-28 16:58 UTC, merged